resources:
# The repo with our Dockerfile
- name: maven-resource
  type: git
  icon: github
  source:
    uri: https://github.com/manishgit138/maven-resource.git
    branch: master

# Where we will push the image
- name: simple-image
  type: registry-image
  icon: docker
  source:
    repository: ((image-repo-name))/simple-image
    username: ((registry-username))
    password: ((registry-password))

jobs:
- name: build-and-push
  plan:
  - get: maven-resource
  - task: build-task-image
    privileged: true
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: vito/oci-build-task
      inputs:
      - name: maven-resource
      outputs:
      - name: image
      params:
        CONTEXT: maven-resource
      run:
        path: build
  - put: simple-image
    params:
      image: image/image.tar
